{{- if .Values.Vault.Tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}.tls
data:
  vault.crt: {{.Values.Vault.Tls.Cert}}
  vault.key: {{.Values.Vault.Tls.Key}}
  vault.ca: {{.Values.Vault.Tls.CA}}
{{- end}}
