---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
{{- if .Values.Vault.NodePort }}
  type: NodePort
{{- end }}
  ports:
    - name: {{.Release.Name}}
      protocol: TCP
{{- if .Values.Vault.Tls }}
      port: 443
      targetPort: 443
{{- else }}
      port: 80
      targetPort: 80
{{- end }}
{{- if .Values.Vault.NodePort }}
      nodePort: {{ .Values.Vault.NodePort }}
{{- end }}
  selector:
    app: {{.Release.Name}}
